# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notes for Computer Vision
email: mt.liyichen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  @COOLA-lab SEU
baseurl: "/CV_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  mt-cly

# Build settings
markdown: kramdown
